name: EarthInTime
version: 1.0
main: com.tuenkle.earthintimeplugin.EarthInTimePlugin
api-version: 1.19
depend: [dynmap]
commands:
  clock:
    description: Clock Command
    usage: /clock give empty, /clock give 600
  나라:
    aliases: [국가]
    description: Nation Command
    usage: /nation set nationName
  메뉴:
    description: 메뉴